### 1. Configurações e Libraries

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

In [17]:
df = pd.read_csv("data/recalls_stellantis_brasil.csv")
df.head()

        Modelo  Ano Fabricacao  Idade Veiculo        Km  Reclamacoes Recall
0    Fiat Toro            2023            3.0   32954.0          2.0    Não
1     Fiat Uno            2016           10.0  117794.0          6.0    Não
2     Fiat Uno            2012           14.0  129392.0          4.0    Não
3  Fiat Strada            2019            7.0   46307.0          3.0    Não
4    Fiat Toro            2017            9.0   79988.0          0.0    Não

### 2. Validação e Pré-processamento do Dataset

In [ ]:
print(f"O Dataset possui {df.shape[1]} colunas e {df.shape[0]} linhas.")

O Dataset possui 6 colunas e 1000 linhas.

In [24]:
df.dtypes

modelo             object
ano_fabricacao      int64
idade_veiculo     float64
km                float64
reclamacoes       float64
recall             object
dtype: object

In [23]:
# Normalização de informações tipo string:

df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")

for col in df.columns:
    if df[col].dtype == "O":
        df[col] = df[col].str.strip().str.lower().str.replace(" ", "_", regex=False)

df.head()

        modelo  ano_fabricacao  idade_veiculo        km  reclamacoes recall
0    fiat_toro            2023            3.0   32954.0          2.0    não
1     fiat_uno            2016           10.0  117794.0          6.0    não
2     fiat_uno            2012           14.0  129392.0          4.0    não
3  fiat_strada            2019            7.0   46307.0          3.0    não
4    fiat_toro            2017            9.0   79988.0          0.0    não

In [ ]:
# Proporção da variável target

pd.DataFrame([df["Recall"].value_counts(), df["Recall"].value_counts(normalize=True)*100]).T

        count  proportion
Recall
Não     702.0        70.2
Sim     298.0        29.8

#### 2.2. Lidando com NULL e colunas extras

In [34]:
df.isna().sum()

modelo            11
ano_fabricacao     0
idade_veiculo      0
km                46
reclamacoes       16
recall             0
dtype: int64

In [ ]:
# Verificando se ano_fabricacao diz sempre a idade do veiculo:
ano_atual = 2026

df[(df["idade_veiculo"] != (ano_atual - df["ano_fabricacao"])) | (df["ano_fabricacao"].isna())]

,modelo,ano_fabricacao,idade_veiculo,km,reclamacoes,recall
5,fiat_uno,2014,NaN,188249.0,1.0,sim
42,jeep_grand_cherokee,2023,NaN,28771.0,1.0,não
53,fiat_strada,2023,NaN,39313.0,1.0,não
69,fiat_strada,2022,NaN,34900.0,1.0,não
155,fiat_toro,2017,NaN,106948.0,7.0,sim
220,jeep_grand_cherokee,2019,NaN,102720.0,5.0,sim
314,fiat_toro,2017,NaN,130624.0,7.0,não
322,jeep_grand_cherokee,2017,NaN,120487.0,7.0,sim
331,jeep_grand_cherokee,2019,NaN,76277.0,9.0,não
385,ram_2500,2019,NaN,98162.0,2.0,não
419,fiat_toro,2020,NaN,81332.0,5.0,não
435,jeep_compass,2023,NaN,34743.0,2.0,não
655,fiat_palio,2016,NaN,100931.0,12.0,sim
732,ram_2500,2015,NaN,140578.0,13.0,sim
772,jeep_grand_cherokee,2018,NaN,87904.0,10.0,sim
803,fiat_palio,2011,NaN,131769.0,6.0,sim
919,jeep_compass,2025,NaN,5833.0,2.0,não
963,fiat_uno,2014,NaN,57058.0,7.0,sim
969,jeep_renegade,2023,NaN,29825.0,1.0,não
983,jeep_compass,2017,NaN,125739.0,7.0,não

In [ ]:
df["idade_veiculo"] = df["idade_veiculo"].fillna(ano_atual - df["ano_fabricacao"])
df = df.drop(columns=["ano_fabricacao"])

        modelo  idade_veiculo        km  reclamacoes recall
0    fiat_toro            3.0   32954.0          2.0    não
1     fiat_uno           10.0  117794.0          6.0    não
2     fiat_uno           14.0  129392.0          4.0    não
3  fiat_strada            7.0   46307.0          3.0    não
4    fiat_toro            9.0   79988.0          0.0    não